[kdcdefaults]
    kdc_ports = 88
    kdc_tcp_ports = 88

[realms]
    EXAMPLE.LOCALHOST = {
        acl_file = /etc/krb5kdc/kadm5.acl
        admin_keytab = /etc/krb5kdc/kadm5.keytab
        supported_enctypes = aes256-cts-hmac-sha1-96:normal aes128-cts-hmac-sha1-96:normal
        max_life = 24h0m0s
        max_renewable_life = 7d0h0m0s
    }
