[libdefaults]
    default_realm = EXAMPLE.LOCALHOST
    dns_lookup_realm = false
    dns_lookup_kdc = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    rdns = false
    udp_preference_limit = 1

[realms]
    EXAMPLE.LOCALHOST = {
        kdc = kdc.example.localhost:88
        admin_server = kdc.example.localhost:749
    }

[domain_realm]
    .example.localhost = EXAMPLE.LOCALHOST
    example.localhost = EXAMPLE.LOCALHOST
